name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies (via npm) and cache them.'
inputs:
  caching:
    description: 'Whether or not to cache dependencies.'
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: 'Whether or not the cache was hit.'
    value: ${{ steps.install.outputs.cache }}
runs: 
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}' >> $GITHUB_OUTPUT"
      shell: bash