name: Matrix Demo
on:
  push:
    branches:
      - main
jobs:
    matrix:
        name: Node ${{ matrix.node-version }} on ${{ matrix.operating-system }}
        continue-on-error: true
        runs-on: ${{ matrix.operating-system }}
        strategy:
          matrix:
            node-version: [14, 16]
            operating-system: [ubuntu-latest, windows-latest, macos-latest]
            include:
              - node-version: 18
                operating-system: ubuntu-latest
            exclude:
              - node-version: 14
                operating-system: macos-latest
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm ci
        - name: Build Project
          run: npm run build
